version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.5.0"
  - dependency-name: Nuke.Common
    versions:
    - 5.1.0
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
    - 2.2.2
