# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core 2.0 SDK
  inputs:
    version: '2.0.x'

- task: UseDotNet@2
  displayName: Install .NET Core 2.1 SDK
  inputs:
    version: '2.1.x'

- task: UseDotNet@2
  displayName: Install .NET Core 2.2 SDK
  inputs:
    version: '2.2.x'

- task: UseDotNet@2
  displayName: Install .NET Core 3.0 SDK
  inputs:
    version: '3.0.x'

- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    version: '3.1.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'src/nuget.config'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'