trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core 2.0 SDK
  inputs:
    version: '2.0.x'

- task: UseDotNet@2
  displayName: Install .NET Core 2.1 SDK
  inputs:
    version: '2.1.x'

- task: UseDotNet@2
  displayName: Install .NET Core 2.2 SDK
  inputs:
    version: '2.2.x'

- task: UseDotNet@2
  displayName: Install .NET Core 3.0 SDK
  inputs:
    version: '3.0.x'

- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    version: '3.1.x'

- task: PowerShell@2
  displayName: Build / Test / Pack
  inputs:
    filePath: 'build/build.ps1'

    
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
